import * as path from 'path';

/**
 * ProcessingCache
 * 
 * Prevents infinite loops by tracking files that WE created.
 * When the file watcher sees a file, it checks this cache.
 * If found, it's our file -> Remove from cache & Ignore.
 * If not found, it's a user file -> Process.
 */
export class ProcessingCache {
    private static cache = new Set<string>();

    /**
     * Mark a file path as "being generated by Upfly".
     * Call this BEFORE writing the file to disk.
     */
    static add(filePath: string) {
        // Normalize path to handle Windows/Unix consistency
        const normalized = path.normalize(filePath);
        this.cache.add(normalized);
    }

    /**
     * Check if a file was generated by Upfly.
     * If true, removes it from the cache (one-time consume) and returns true.
     */
    static consume(filePath: string): boolean {
        const normalized = path.normalize(filePath);
        if (this.cache.has(normalized)) {
            this.cache.delete(normalized);
            return true;
        }
        return false;
    }
}
